name: Arduino Build

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install PySerial
        run: |
          pip3 install pyserial

      - name: Config Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
      
      - name: Install ESP32 Board
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@2.0.14
      - name: Install Arduino Library
        run: |
          arduino-cli lib install "Adafruit NeoPixel"@1.12.0
          arduino-cli lib install "ArduinoJson"@7.0.4
      

      - name: Copy library to Arduino library folder
        run: |
          cp Metro -r  /home/runner/Arduino/libraries
      


      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32c3 ./ --build-path ../
      - name: Copy Bin
        run: |
          cd ../
          cp esp32.ino.bin ./esp32/esp32.ino.bin
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: esp32.ino.bin
      - name: Tar
        run: |
          tar -czf esp32.ino.bin.${{ steps.get_version.outputs.VERSION }}.tar.gz esp32.ino.bin
      - name: Get version
        id: get_version
        # run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT
        
      - name: Upload to oss
        id: upload_to_oss
        uses: tvrcgo/upload-to-oss@master
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-cn-shanghai
          bucket: casaos
          assets: |
            esp32.ino.bin.tar.gz:/IceWhaleTech/IceWhale-Esp32/releases/download/${{ steps.get_version.outputs.VERSION }}/esp32.ino.bin.tar.gz
