name: Arduino Build

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install PySerial
        run: |
          pip3 install pyserial

      - name: Config Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
      
      - name: Install ESP32 Board
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@2.0.14
      - name: Install Arduino Library
        run: |
          arduino-cli lib install "Adafruit NeoPixel"@1.12.0
          arduino-cli lib install "ArduinoJson"@7.0.4
      

      - name: Copy library to Arduino library folder
        run: |
          cp Metro -r  /home/runner/Arduino/libraries
      


      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32c3 ./ --build-path ../
      - name: Copy Bin
        run: |
          cd ../
          cp esp32.ino.bin ./esp32/esp32.ino.bin
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: esp32.ino.bin