name: Arduino Build

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install PySerial
        run: |
          pip3 install pyserial

      - name: Install Arduino Library
        run: |
          arduino-cli lib install "Adafruit NeoPixel"@1.12.0
          arduino-cli lib install "ArduinoJson"@7.0.4
      

      - name: test
        run: |
          arduino-cli config dump

      - name: Copy library to Arduino library folder
        run: |
          cp Metro -r  /home/runner/Arduino/libraries
      
      
      
      - name: cd to parent directory
        run: |
          cd ..
      - name: test
        run: |
          ls /home/runner/Arduino/libraries
          arduino-cli config dump


      - name: Compile Sketch
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32s3 --build-path ./esp32 ./esp32
      - name: test
        run: |
          cd ./esp32
          ls
